services:
  external-server:
    build: "/home/jiri-strouhal/Plocha/external-server"
    entrypoint:
      [
        "python3",
        "/home/bringauto/external_server/external_server_main.py",
        "-c",
        "./config/config.json",
      ]
    volumes:
      - "./config/external-server:/home/bringauto/external_server/config"
      - "./log/external-server:/home/bringauto/external_server/log"
    restart: "always"
    depends_on:
      - http-api
    networks:
      - external-server-test

  http-api:
    image: bringauto/fleet-protocol-http-api:v2.6.0
    ports:
      - 8080:8080
    restart: "no"
    depends_on:
      postgresql-database:
        condition: service_healthy
    networks:
      - external-server-test
    volumes:
      - ./config/http-api/config.json:/usr/src/app/config.json
    entrypoint:
      [
        "python3",
        "-m",
        "server",
        "config.json",
        "--location=postgresql-database",
      ]

  postgresql-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 0.5s
    networks:
      - external-server-test
    ports:
      - 5432:5432
    volumes:
      - ./db/insert_test_api_key.sh:/docker-entrypoint-initdb.d/insert_test_api_key.sh

networks:
  external-server-test:
    name: external-server-test
